#################################
#####        延时聊天       #####
#################################
delayChat:
  maxSaves: 30                  #延时显示的最大保存条数,>=0
  interval: 10                 #延时显示的间隔,单位tick,>=1
  prefix: "&7↑"          #延时显示的聊天信息前缀,可为空(会加到整个聊天信息前,包括玩家名)