#################################
#####          语言         #####
#################################
lang:
  cn: "lang_cn.yml"

#################################
#####          显示         #####
#################################
show:
  chatFuncPrefix: "#"           #聊天功能类型前缀
  deadLoopLevel: 5              #重复调用几层判定为死循环,>=1
  cancel:                       #检测退出页面
    interact: true              #玩家与方块交互时
    animation: false            #玩家挥动手时
    attack: true                #玩家攻击或受攻击时
    chat: false                 #玩家聊天时
    chatCancel: true            #chat为false时,玩家在显示界面时是否取消其发出的聊天信息
    shoot: true                 #发射时
  maxBackPage: 10               #最大保存的返回页面数,>=0
  line: 25                      #页面行数,补的空行数=line-有内容的行数,>=1
  fancymessage:
    add: 730
    operateTipMenu: 710
    operateTipEmpty: 715
    pageControl: 720
    listControl: 725

#################################
#####        延时聊天       #####
#################################
delayChat:
  maxSaves: 30                  #延时显示的最大保存条数,>=0
  interval: 10                 #延时显示的间隔,单位tick,>=1
  prefix: "&7↑"          #延时显示的聊天信息前缀,可为空(会加到整个聊天信息前,包括玩家名)
  